### ISSUE TITLE
help for installing bountysource

### ISSUE THREAD

**Issue by sucof** [shadiakiki1986/test-bountysource#1]
hi, shadiakiki1986, when install bountysource/core, there are some mistake,
RI::InvalidURIError - bad URI(is not URI?): :
  /home/ro4k/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split'
  /home/ro4k/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
  /home/ro4k/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
  config/routes.rb:10:in `block (2 levels) in <top (required)>'
  actionpack (4.0.13) lib/action_dispatch/routing/mapper.rb:37:in `block in matches?'
  actionpack (4.0.13) lib/action_dispatch/routing/mapper.rb:35:in `matches?'
  actionpack (4.0.13) lib/action_dispatch/routing/mapper.rb:44:in `call'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:676:in `call'
  lib/middleware/force_accept_header.rb:11:in `call'
  newrelic_rpm (3.8.0.218) lib/new_relic/rack/error_collector.rb:55:in `call'
  newrelic_rpm (3.8.0.218) lib/new_relic/rack/agent_hooks.rb:32:in `call'
  newrelic_rpm (3.8.0.218) lib/new_relic/rack/browser_monitoring.rb:27:in `call'
  rack (1.5.5) lib/rack/deflater.rb:25:in `call'
  api-versions (1.2.0) lib/api-versions/middleware.rb:22:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.13) lib/action_dispatch/middlewa

and the code are:
  lambda_api_host = lambda { |request| request.host == URI.parse(Api::Application.config.api_url).host }
  lambda_api_force_ssl = lambda { |request| !request.ssl? && URI.parse(Api::Application.config.api_url).scheme == 'https' }
  lambda_salt_host = lambda { |request| request.host == URI.parse(Api::Application.config.salt_url).host }
  lambda_salt_force_ssl = lambda { |request| !request.ssl? && URI.parse(Api::Application.config.salt_url).scheme == 'https' }
  lambda_www_host = lambda { |request| request.host == URI.parse(Api::Application.config.www_url).host }
  lambda_www_force_ssl = lambda { |request| !request.ssl? && URI.parse(Api::Application.config.www_url).scheme == 'https' }
  lambda_short_host = lambda { |request| request.host == URI.parse(Api::Application.config.short_url).host }

Do you have installed it successfully?

**Comment by shadiakiki1986** [comment]
No I didn't continue trying to get it work because it required too many environment variables, even for a minimal setup, or at least that was my impression
